name: Artifacts

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  upload:
    runs-on: windows-latest

    steps:
      - name: createfile
        run: |
          Set-location $ENV:GITHUB_WORKSPACE
          New-Item "freddy" -ItemType Directory | Out-Null
          set-location "freddy"
          "Dette er en test" | Set-Content "myfile.txt"

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: freddy
          path: freddy

  download:
    runs-on: windows-latest

    steps:
      - name: download
        run: |
          $headers = @{ 
            "Authorization" = "token ${{github.token}}"
            "Accept"        = "application/vnd.github.v3+json"
          }
          $url = "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/actions/artifacts"
          $artifacts = (Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri $url | ConvertFrom-Json).artifacts
          $artifacts.name | Out-host
          

