name: Authentication test

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create dockerfile
        id: createdockerfile
        run: |
          $alGoHelperPath = "$([System.IO.Path]::GetTempFileName()).ps1"
          $webClient = New-Object System.Net.WebClient
          $webClient.CachePolicy = New-Object System.Net.Cache.RequestCachePolicy -argumentList ([System.Net.Cache.RequestCacheLevel]::NoCacheNoStore)
          $webClient.DownloadFile('https://raw.githubusercontent.com/freddydk/AL-Go-Actions/main/AL-Go-Helper.ps1', $alGoHelperPath)
          . $alGoHelperPath -local
          DownloadAndImportBcContainerHelper
          $artifactUrl = get-bcartifacturl -country us 
          $folder = Join-Path $ENV:GITHUB_WORKSPACE 'buildfolder'
          $imageName = New-BcImage -artifactUrl $artifactUrl -imageName 'my' -populateBuildFolder $folder
          Add-Content -Path $ENV:GITHUB_OUTPUT -value "folder=$folder"
          Add-Content -Path $ENV:GITHUB_OUTPUT -value "imageName=$imageName"

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: buildfolder
          push: true
          tags: '${{steps.createdockerfile.outputs.imageName}}'
          cache-from: type=gha
          cache-to: type=gha,mode=max
