name: CITest

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [main]
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: env
        run: |
          dir env:

      - name: analyze
        run: |
          set-location $ENV:GITHUB_WORKSPACE
          get-childitem -recurse | out-host
          $env:GITHUB_USER = '${{ github.actor }}'
          $env:GITHUB_TOKEN = '${{ github.token }}'
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          invoke-git config --global hub.protocol https
          git diff --name-only --diff-filter=ACMDRT ${{ github.event.pull_request.base.sha }} HEAD
