name: 'æøå workflow'

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [mainx]
  pull_request:
    paths-ignore:
      - 'README.md'
    branches: [mainx]
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: env
        run: |
          dir env:

      - name: analyze
        run: |
          $actor = '${{ github.actor }}'
          $token = '${{ github.token }}'
          $headers = @{             
              "Authorization" = "token $token"
              "Accept" = "application/vnd.github.baptiste-preview+json"
          }
          if ($ENV:GITHUB_EVENT_NAME -eq "workflow_dispatch") {
            Write-Host "BUILD ALL"
          }
          else {
            if ($ENV:GITHUB_EVENT_NAME -eq "pull_request") {
              $url = "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/compare/${{ github.event.pull_request.base.sha }}...${{ github.sha }}"
            }
            else {
              $url = "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/compare/${{ github.event.before }}...${{ github.event.after }}"
            }
            Write-Host $url
            $response = Invoke-WebRequest -Headers $headers -UseBasicParsing -Method GET -Uri $url | ConvertFrom-Json
            $response | ConvertTo-Json
            $response.files.filename
            $response.commits.sha
            $response.commits | % {
              $commit = $_
              Write-Host $commit.sha
              Write-Host $commit.commit
            }
          }
