name: CITest

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [main]
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: env
        run: |
          dir env:

      - name: analyze
        run: |
          $actor = '${{ github.actor }}'
          $token = '${{ github.token }}'
          $headers = @{             
              "Authorization" = "token $token"
              "Accept" = "application/vnd.github.baptiste-preview+json"
              "per_page" = "100"
              "page" = "1"
          }
          $response = Invoke-WebRequest -Headers $headers -UseBasicParsing -Method GET -Uri "https://api.github.com/repos/freddydk/Test/compare/${{ github.event.pull_request.base.sha }}...${{ github.sha }}" | ConvertFrom-Json
          $response | ConvertTo-Json
          $response.files.filename
          $headers = @{             
              "Authorization" = "token $token"
              "Accept" = "application/vnd.github.baptiste-preview+json"
              "per_page" = "100"
              "page" = "2"
          }
          $response = Invoke-WebRequest -Headers $headers -UseBasicParsing -Method GET -Uri "https://api.github.com/repos/freddydk/Test/compare/${{ github.event.pull_request.base.sha }}...${{ github.sha }}" | ConvertFrom-Json
          $response | ConvertTo-Json
          $response.files.filename
