name: Context

on:
  workflow_dispatch:

defaults:
  run:
    shell: PwSh

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: GCI
        run: |
          Get-ChildItem 'c:\modules' -recurse | out-host

      - name: ENV
        run: |
          Write-Host "ModulePath: '$ENV:PSModulePath'"
          Write-Host "GITHUB_EVENT_PATH: '$ENV:GITHUB_EVENT_PATH'"
          Get-Module Az.KeyVault -ListAvailable         
          Get-Module AzureRM.KeyVault -ListAvailable         

      - name: Remove AzureRM
        run: |
          Write-Host 'C:\\Modules\Az_*'
          if (Test-Path 'C:\\Modules\Az_*' -pathType Container) {
            $modulePath = (Get-Item 'C:\\Modules\Az_*').FullName
            Write-Host $modulePath
            $ENV:PSModulePath = "$modulePath;$("$ENV:PSModulePath".Split(';') | Where-Object { $_ -notlike 'C:\\Modules\Azure*' } -join ';')"
            Write-Host $ENV:PSModulePath
          }
          else {
            Write-Host "NOT EXIST"
          }

      - name: ENV
        run: |
          Write-Host "ModulePath: '$ENV:PSModulePath'"
          Write-Host "GITHUB_EVENT_PATH: '$ENV:GITHUB_EVENT_PATH'"
          Get-Module Az.KeyVault -ListAvailable         
          Get-Module AzureRM.KeyVault -ListAvailable         

      - name: ENV
        run: |
          dir env:

      - name: mask
        run: |
          Write-Host -nonewline "This is a test"
          Write-Host "`r::add-mask::Freddy"

      - name: print
        run: |
          Write-Host "Freddy Kristiansen"

      - name: event
        run: |
          Get-Content "$ENV:GITHUB_EVENT_PATH" -encoding UTF8

      - name: Echo on private
        run: echo "I am private"
        if: ${{github.event.repository.private}}
