name: Context

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  update:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      - name: ComputerInfo
        run: |
          Get-ComputerInfo | Out-Host

      - name: VAR
        env:
          settings: ${{ VARS.ALGOSETTINGS }}
        run: |
          Write-Host "------------"
          Write-Host $ENV:settings
          Write-Host "------------"
          if ($ENV:settings) {
            Write-Host "SET"
          }

      - name: ENV
        run: |
          Write-Host "ModulePath: '$ENV:PSModulePath'"
          Write-Host "GITHUB_EVENT_PATH: '$ENV:GITHUB_EVENT_PATH'"
          Get-Module Az.KeyVault -ListAvailable         
          Get-Module AzureRM.KeyVault -ListAvailable         

      - name: Remove AzureRM
        run: |
          $azModulesPath = Get-ChildItem 'C:\Modules\az_*' -Directory
          if ($azModulesPath) {
            Write-Host $azModulesPath.FullName
            $ENV:PSModulePath = "$($azModulesPath.FullName);$(("$ENV:PSModulePath".Split(';') | Where-Object { $_ -notlike 'C:\\Modules\Azure*' }) -join ';')"
            Add-Content -Path $env:GITHUB_ENV -Value "PSModulePath=$ENV:PSModulePath"
            Write-Host $ENV:PSModulePath
          }
          else {
            Write-Host "NOT EXIST"
          }
 
      - name: ENV
        run: |
          Write-Host "ModulePath: '$ENV:PSModulePath'"
          Write-Host "GITHUB_EVENT_PATH: '$ENV:GITHUB_EVENT_PATH'"
          Get-Module Az.KeyVault -ListAvailable         
          Get-Module AzureRM.KeyVault -ListAvailable         

      - name: ENV
        run: |
          dir env:

      - name: mask
        run: |
          Write-Host -nonewline "This is a test"
          Write-Host "`r::add-mask::Freddy"

      - name: print
        run: |
          Write-Host "Freddy Kristiansen"

      - name: event
        run: |
          Get-Content "$ENV:GITHUB_EVENT_PATH" -encoding UTF8

      - name: Echo on private
        run: echo "I am private"
        if: ${{github.event.repository.private}}

      - name: GCI
        run: |
          Get-ChildItem 'c:\modules' -recurse | out-host

  update2:
    runs-on: windows-latest

    steps:
      - name: ComputerInfo
        run: |
          Get-ComputerInfo | Out-Host

      - name: DownloadTest
        run: |
          get-process

      - name: ENV
        run: |
          Write-Host "ModulePath: '$ENV:PSModulePath'"
          Write-Host "GITHUB_EVENT_PATH: '$ENV:GITHUB_EVENT_PATH'"
          Get-Module Az.KeyVault -ListAvailable         
          Get-Module AzureRM.KeyVault -ListAvailable         

  update3:
    runs-on: ubuntu-latest

    steps:
      - name: ComputerInfo
        run: |
          cat /proc/meminfo
          sudo lshw

      - name: DownloadTest
        run: |
          $ProgressPreference = "SilentlyContinue"
          cat /proc/vmstat

      - name: GCI
        run: |
          $ProgressPreference = "SilentlyContinue"
          (Get-ChildItem -path /home -directory).FullName


