name: Context

on:
  workflow_dispatch:
  pull_request:
  push:

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: ENV
        run: |
          dir env:
    
      - name: Echo on private
        run: echo "I am private"
        if: ${{github.event.repository.private}}
