name: Dir

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: GCI
        run: |
          Set-location "c:\"
          Get-ChildItem
          Add-Content -Path $env:GITHUB_ENV -Value "TESTENV=FREDDY"

      - name: GCI2
        run: |
          Write-Host "ENVVAR $ENV:TESTENV"

      - name: Get-InstalledModule
        run: |
          Get-InstalledModule

      - name: Get-Module
        run: |
          Get-Module

      - name: Get-Module-ListAvailable
        run: |
          Get-Module -Name 'AzureRM.KeyVault' -ListAvailable

      - name: ReadFromKeyVault
        run: |
          $azureCredentials = '${{ Secrets.Azure_Credentials }}' | ConvertFrom-Json
          $azureCredentials.KeyVaultName
          Get-Module -Name 'AzureRM.KeyVault' -listAvailable | Import-Module
          Get-Module -Name 'AzureRM.Profile' -listAvailable | Import-Module
          Clear-AzureRmContext -Scope Process
          Clear-AzureRmContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
          $credential = New-Object PSCredential -argumentList $azureCredentials.clientId, (ConvertTo-SecureString $azureCredentials.clientSecret -AsPlainText -Force)
          Connect-AzureRmAccount -ServicePrincipal -Tenant $azureCredentials.tenantId -Credential $credential | Out-Null
          Set-AzureRmContext -Subscription $azureCredentials.subscriptionId -Tenant $azureCredentials.tenantId | Out-Null
          $keyVaultSecret = Get-AzureRmKeyVaultSecret -VaultName $azureCredentials.keyVaultName -Name 'Password'
          if ($keyVaultSecret) {
            $value = [Runtime.InteropServices.Marshal]::PtrToStringBSTR(([Runtime.InteropServices.Marshal]::SecureStringToBSTR($keyVaultSecret.SecretValue)))
            Write-Host "The password is $value"
          }
          else {
            Write-Host "No password secret available"
          }
         
