name: Encoding

on:
  workflow_dispatch:

defaults:
  run:
    shell: powershell

jobs:
  output:
    runs-on: windows-latest

    steps:
      - name: Echo
        run: |
          echo 'aäoöuü'

      - name: WriteHost
        run: |
          Write-Host 'aäoöuü'

      - name: Info
        run: |
          $OutputEncoding = [console]::OutputEncoding
          $InputEncoding = [console]::InputEncoding
          echo $OutputEncoding
          echo $InputEncoding
