name: Encoding

on:
  workflow_dispatch:

defaults:
  run:
    shell: powershell

jobs:
  output:
    runs-on: windows-latest

    steps:
      - name: Echo
        run: |
          echo 'aäoöuü'

      - name: WriteHost
        run: |
          Write-Host 'aäoöuü'

      - name: Info
        run: |
          $OutputEncoding = [console]::OutputEncoding
          $InputEncoding = [console]::InputEncoding
          echo $OutputEncoding
          echo $InputEncoding

      - name: Decode
        run: |
          $encText = "YcOkb8O2dcO8"
          $DecodedText = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($encText))
          Write-Host $DecodedText
