name: Fromjson

on:
  workflow_dispatch:

permissions:
  actions: write

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      city: ${{ fromJson(steps.makejson.outputs.json).city }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: MakeJson
        id: makejson
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          Add-Content -Path $env:GITHUB_OUTPUT -Value 'json={"user":"freddy","city":"helsinge"}'
          gh secret set MYSECRET --body "gurli"

      - name: City
        env:
          city: ${{ fromJson(steps.makejson.outputs.json).city }}
        run: |
          Write-Host $ENV:city

      - name: SUMMARY
        env:
          city: ${{ fromJson(steps.makejson.outputs.json).city }}
        run: |
          Add-Content -path $ENV:GITHUB_STEP_SUMMARY -value "# Title`n`nOpen https://www.google.com to authenticate to $($ENV:city)"

  test2:
    runs-on: ubuntu-latest
    name: Click here to authenticate for deploying to ${{ needs.test.outputs.city }}
    needs: [ test ]
    steps:
      - name: SUMMARY
        env:
          city: 'xxx'
        run: |
          Add-Content -path $ENV:GITHUB_STEP_SUMMARY -value "Open https://www.google.com to authenticate to $($ENV:city)"

      - name: wait
        run: |
          $secret = '${{ secrets.TESTSECRET }}'
          Write-Host $secret.ToUpperInvariant()
          1..1 | % {
            Start-Sleep -seconds 10
            $secret = '${{ secrets.TESTSECRET }}'
            Write-Host $secret.ToUpperInvariant()
            Write-Host "Please respond on https://www.google.com"
          }

  test3:
    runs-on: ubuntu-latest
    name: Deploying
    needs: [ test2 ]
    steps:
      - name: wait
        run: |
          $secret = '${{ secrets.TESTSECRET }}'
          Write-Host $secret.ToUpperInvariant()
          $secret = '${{ secrets.MYSECRET }}'
          Write-Host $secret.ToUpperInvariant()
