name: Fromjson

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: MakeJson
        id: makejson
        run: |
          Add-Content -Path $env:GITHUB_OUTPUT -Value 'json={"user":"freddy","city":"helsinge"}'

      - name: wait
        run: |
          Write-Host "::warning::please respond"
          1..100 | % {
            Start-Sleep -seconds 10
            Write-Host "Please respond on https://www.google.com"
          }
          
      - name: City
        env:
          city: ${{ fromJson(steps.makejson.outputs.json).city }}
        run: |
          Write-Host $ENV:city

  test2:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: yep
        run: |
          Write-Host "GO"
