name: Fromjson

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      city: ${{ fromJson(steps.makejson.outputs.json).city }}
    steps:
      - name: MakeJson
        id: makejson
        run: |
          Add-Content -Path $env:GITHUB_OUTPUT -Value 'json={"user":"freddy","city":"helsinge"}'

      - name: City
        env:
          city: ${{ fromJson(steps.makejson.outputs.json).city }}
        run: |
          Write-Host $ENV:city

      - name: info
        env:
          city: ${{ fromJson(steps.makejson.outputs.json).city }}
        run: |
          Write-Host "::Warning"::Open https://www.google.com to authenticate to $($ENV:city)"

  test2:
    runs-on: ubuntu-latest
    name: Click here to authenticate for deploying to ${{ needs.test.outputs.city }}
    needs: [ test ]
    steps:
      - name: wait
        run: |
          Write-Host "::warning::please respond"
          1..10 | % {
            Start-Sleep -seconds 10
            Write-Host "Please respond on https://www.google.com"
          }

  test3:
    runs-on: ubuntu-latest
    name: Deploying
    needs: [ test2 ]
    steps:
      - name: wait
        run: |
          Write-Host "::info::done"
