name: Fromjson

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: MakeJson
        id: makejson
        run: |
          Add-Content -Path $env:GITHUB_OUTPUT -Value 'json={"user":"freddy","city":"helsinge"}'

      - uses: step-security/wait-for-secrets@v1
        id: wait-for-secrets
        with:
          secrets: |
            OTP: 
              name: 'OTP to publish package'
              description: 'OTP from authenticator app'
          
      - name: City
        env:
          city: ${{ fromJson(steps.makejson.outputs.json).city }}
        run: |
          Write-Host $ENV:city

  test2:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: yep
        run: |
          Write-Host "GO"
