name: Pull image test

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Init cache
        uses: satackey/action-docker-layer-caching@v0.0.11
          continue-on-error: true
          with:
            key: bcdocker-{hash}
            restore-keys: |
              bcdocker-

      - name: Pull image
        run: |
          docker pull ghcr.io/freddydk/businesscentral:sandbox-21.4.52563.53052-us


