name: Secrets

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: GetSecret
        run: |
          $testSecret = '${{ secrets.TESTSECRET }}'
          $testSecret.ToCharArray() | % { Write-Host -NoNewline "$_ " }

      - name: GH
        run: |
          .\setsecret.ps1 -token '${{ secrets.GHTOKENWORKFLOW }}'

      - name: GetSecret
        run: |
          $testSecret = '${{ secrets.TESTSECRET }}'
          $testSecret.ToCharArray() | % { Write-Host -NoNewline "$_ " }
