name: Secrets

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: GetSecret
        run: |
          $testSecret = '${{ secrets.TESTSECRET }}'
          $bytes = [System.Text.Encoding]::ASCII.GetBytes($testSecret)
          $testSecret2 = [System.Text.Encoding]::UTF8.GetString($bytes)
          $testSecret.ToCharArray() | % { Write-Host -NoNewline "$_ " }
          $testSecret2.ToCharArray() | % { Write-Host -NoNewline "$_ " }
