name: Secrets

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: GetSecret
        run: |
          $testSecret = '${{ secrets.TESTSECRET }}'
          $testSecret.ToCharArray() | % { Write-Host -NoNewline "$_ " }

      - name: GH
        run: |
          gh version
          $token = '${{ github.token }}'
          $token | gh auth login --with-token
          'NYSECRET' | gh secret set TESTSECRET

      - name: GetSecret
        run: |
          $testSecret = '${{ secrets.TESTSECRET }}'
          $testSecret.ToCharArray() | % { Write-Host -NoNewline "$_ " }
