name: Simple Matrix

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  Country:
    runs-on: windows-latest
    strategy:
      matrix:
        country: [ 'DK', 'US', 'DE' ]
        os: [ '2019', '2016' ]
    steps:
    - name: Output country
      run: |
        Write-Host '${{ matrix.os }} ${{ matrix.country }}'
