name: Simple Matrix

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  Environments:
    runs-on: windows-latest
    outputs:
      environments: ${{steps.Environments.outputs.environments}}
    steps:
    - name: environments
      id: environments
      run: |
        $environments = @( @{ "environmentName" = "google"; "url" = "http://www.google.com"}, @{ "environmentName" = "bing"; "url" = "http://www.bing.com" } ) | ConvertTo-Json -compress
        Write-Host "::set-output name=environments::$($environments | ConvertTo-Json -compress)"
        $json = $environments | ConvertTo-Json -compress
        write-host $json
  Country:
    runs-on: windows-latest
    needs: [ Environments ]
    strategy:
      matrix:
        country: [ 'dk','us' ]
        os: [ '2019', '2016' ]
    steps:
    - name: Output country
      run: |
        Write-Host '${{toJson(fromJson(needs.Environments.outputs.environments).*.environmentName)}}'
        Write-Host '${{ matrix.os }} ${{ matrix.country }}'
