name: Test3

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

permissions:
  contents: read
  id-token: write

jobs:
  Testjob:
    runs-on: ubuntu-latest

    steps:
      - name: Investigate
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
        run: |
          az login --service-principal -u $ENV:CLIENT_ID --tenant $ENV:TENANT_ID --allow-no-subscriptions
          az account list

