name: Test3

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  Testjob:
    runs-on: ubuntu-latest

    steps:
      - name: Investigate
        run: |
          

