name: Test3

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

permissions:
  contents: read
  id-token: write

jobs:
  Testjob:
    runs-on: ubuntu-latest

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Investigate
        run: |
          az account list

