name: Test3

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

permissions:
  contents: read
  id-token: write

jobs:
  Testjob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: LoginPS
        run: |
          . ./bcauth.ps1
          $token = Invoke-RestMethod -Method GET -Headers @{ "Authorization" = "bearer $ENV:ACTIONS_ID_TOKEN_REQUEST_TOKEN" } -Uri "$ENV:ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange"
          New-BcAuthContext -ClientID '${{ secrets.CLIENT_ID }}' -ClientAssertion $token.value -Scopes 'https://api.partner.microsoft.com/.default'
          #az login --service-principal --username '${{ secrets.CLIENT_ID }}' --tenant '${{ secrets.TENANT_ID }}' --federated-token $token.value --allow-no-subscriptions
          #az account list
          #$response = az account get-access-token
          #$accesstoken = ($response | ConvertFrom-Json).accesstoken

