name: Test3

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  Testjob:
    runs-on: windows-latest

    steps:
      - name: Investigate
        run: |
          

