name: Test Test Action

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  job0:
    runs-on: windows-latest
    outputs:
      fun: ${{steps.fun.outputs.fun}}
    steps:
    - name: fun
      id: fun
      run: |
        $fun = [ordered]@{
          "name" = "test"
          "uses" = "freddydk/Test/Action@main"
          } | convertto-json -compress
        Write-Host "::set-output name=fun::$fun"
        Write-Host "set-output name=fun::$fun"

  job1:
    runs-on: windows-latest
    needs: [job0]
    steps:
    - name: test
      uses: freddydk/Test/Action@main
      with:
        s1: 'S1'

  job2:
    runs-on: windows-latest
    needs: [job0]
    steps: ${{fromjson(needs.job0.outputs.fun)}}

