name: Test4

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  Testjob:
    runs-on: windows-latest

    steps:
      - name: Test
        run: |
          $test = "GURLI1`nTEST2=GURLI2"
          Add-Content -encoding utf8 -path $env:GITHUB_ENV -value "TEST1=$test"
          Write-Host $env:TEST1
          Write-Host $env:TEST2

      - name: Test2
        run: |
          Write-Host $env:TEST1
          Write-Host $env:TEST2
