name: Test Test Action

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  job0:
    runs-on: windows-latest
    outputs:
      fun: ${{steps.fun.outputs.fun}}
    steps:
    - name: fun
      id: fun
      run: |
        Write-Host "::set-output name=fun::freddydk/Test/Action@main"
        Write-Host "set-output name=fun::freddydk/Test/Action@main"

  job1:
    runs-on: windows-latest
    needs: [job0]
    steps:
    - name: test
      uses: freddydk/Test/Action@main
      with:
        s1: 'S1'

  job2:
    runs-on: windows-latest
    needs: [job0]
    steps: 
      - name: test2
        uses: ${{needs.job0.outputs.fun}}

