name: Test

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  Test job:
    runs-on: windows-latest

    steps:
      - name: inline
        run: |
          Write-Host "::warning file=.github/workflows/Test.yaml::This is a warning"

      - name: Test
        uses: freddydk/Test/Action@main
        with:
          s1: 'Freddy'
          s2: 'Kristiansen'
