name: TestResults

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  Testjob:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'TestResult.xml'
