name: TransferSecret

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  job1:
    runs-on: windows-latest
    outputs:
      authContext: ${{ steps.authContext.outputs.authContext}}
    steps:
      - name: authContext
        id: authContext
        run: |
          $authContext = 'MyPassword'
          $token = '${{ github.token }}'
          Write-Host $token.SubString(1)

          $token = ($token.SubString(5))*2
          $encryptionKey = [System.Text.Encoding]::UTF8.GetBytes($token.SubString(0,16))
          $secStr = ConvertTo-SecureString -String $authContext -AsPlainText -Force
          $encStr = ConvertFrom-SecureString -SecureString $secStr -Key $encryptionKey
          Add-Content -Path $env:GITHUB_OUTPUT -Value "authContext=$encStr"

  job2:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    steps:
      - name: getit
        env:
          authContext: ${{ needs.job1.outputs.authContext }}
        run: |
          $token = '${{ github.token }}'
          Write-Host $token.SubString(1)
          $token = ($token.SubString(5))*2
          $encryptionKey = [System.Text.Encoding]::UTF8.GetBytes($token.SubString(0,16))
          $secStr = ConvertTo-SecureString -String $env:authContext -Key $encryptionKey
          $plainStr = [Runtime.InteropServices.Marshal]::PtrToStringBSTR([Runtime.InteropServices.Marshal]::SecureStringToBSTR($secStr))
          Write-Host $plainStr



