name: TransferSecret

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  job1:
    runs-on: windows-latest
    outputs:
      authContext: ${{ steps.authContext.outputs.authContext}}
    steps:
      - name: authContext
        id: authContext
        run: |
          $authContext = '${{ github.token }}'
          $encryptionKey = '${{ github.token }}'
          $secStr = ConvertTo-SecureString -String $authContext -AsPlainText -Force
          $encStr = ConvertFrom-SecureString -SecureString $secStr -Key $encryptionKey
          Add-Content -Path $env:GITHUB_OUTPUT -Value "authContext=$encStr"

  job2:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    steps:
      - name: getit
        env:
          authContext: ${{ needs.job1.outputs.authContext }}
        run: |
          Write-Host $env:authContext



