name: VARS

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Secret'
        required: false
        default: ''

defaults:
  run:
    shell: pwsh

jobs:
  Testjob:
    runs-on: ubuntu-latest

    steps:
      - name: Mask input
        env:
          _secret: ${{ github.event.inputs.token }}
        run: |
          Write-Host $env:_secret
          Write-Host "::add-mask::$env:_secret"
          Write-Host $env:_secret

      - name: Test1
        env:
          _secrets: ${{ tojson(secrets) }}
          _vars: ${{ tojson(vars) }}
        run: |
          Write-Host "secrets=$env:_secrets"
          Write-Host "vars=$env:_vars"

  Testjob2:
    needs: Testjob
    runs-on: windows-latest
    environment: Test
    steps:
      - name: Test2
        id: Test2
        if: false
        env:
          _secrets: ${{ tojson(secrets) }}
          _vars: ${{ tojson(vars) }}
          Testvar: 'test'
        run: |
          Write-Host "secrets=$env:_secrets"
          Write-Host "vars=$env:_vars"
          Write-Host "vars=$env:Testvar"
          Add-Content -encoding UTF8 -path $env:GITHUB_OUTPUT -value "Testvar2=test2"

      - name: Test3
        env:
          _Testvar2: ${{ steps.Test2.outputs.Testvar2 }}
        run: |
          Write-Host "secrets=$env:_secrets"
          Write-Host "vars=$env:_vars"
          Write-Host "vars=$env:Testvar"
          Write-Host "Testvar2=$env:_Testvar2"
