name: VARS

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  Testjob:
    runs-on: windows-latest

    steps:
      - name: Test1
        env:
          _secrets: ${{ tojson(secrets) }}
          _vars: ${{ tojson(vars) }}
        run: |
          Write-Host "secrets=$env:_secrets"
          Write-Host "vars=$env:_vars"

  Testjob2:
    runs-on: windows-latest
    environment: Test
    steps:
      - name: Test2
        env:
          _secrets: ${{ tojson(secrets) }}
          _vars: ${{ tojson(vars) }}
        run: |
          Write-Host "secrets=$env:_secrets"
          Write-Host "vars=$env:_vars"
